server:
  port: 8090

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/secondhandgoodsmanagement?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
  web:
    resources:
      static-locations: classpath:/static/, file:static/
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  thymeleaf:
    cache: false #使用Thymeleaf模板引擎，关闭缓存
mybatis:
  type-aliases-package: com.example.back.entity
  mapper-locations: classpath:/mybatis/*.xml

